@isTest
public class enqMeetOnlineLWCTest {
/*
    @isTest
    static void testGetEnquiryName() {
        // Create test data for Enquiry__c
        Lead testLead = new Lead(LastName = 'Test Lead', Company = 'Test Company');
        insert testLead;
        
        Account testSchool = new Account(Name = 'Test School');
        insert testSchool;
        
        Contact testContact = new Contact(LastName = 'Test Contact', AccountId = testSchool.Id, Lead__c = testLead.Id);
        insert testContact;
        
        Enquiry__c testEnquiry = new Enquiry__c(Name = 'Test Enquiry', Contact__c = testContact.Id, Lead__c = testLead.Id);
        insert testEnquiry;
        
        String schoolShortCode = 'TESTCODE';

        // Call the method
        Test.startTest();
        Map<String, Object> result = enqMeetOnlineLWC.getEnquiryName(testEnquiry.Id);
        Map<String, Object> result1 = enqMeetOnlineLWC.re_schgetEnquiryName(testEnquiry.Id);
        List<String> result2 = enqMeetOnlineLWC.getSubjectPicklistValues();
        List<User> result3 = enqMeetOnlineLWC.getLeadUser(schoolShortCode);
        Test.stopTest();

    }*/
}