@isTest

public class StageProgressBarControllerTest {
      Static testmethod void StatusProgressBarController(){
          
         StatusProgressBarController.testmethod1();
          
     /*     Enquiry__c enq= new Enquiry__c();
          enq.FirstName__c = 'testfirstName';
          enq.Last_Name__c = 'testLastName';
        
          enq.Stages__c = 'Enquiry';
          insert enq;
          
          StatusProgressBarController spc = new StatusProgressBarController();
          
          
          spc.setselectedField(enq.Last_Name__c);
          spc.getselectedField();
          spc.currentStatus = spc.getselectedField();
          spc.GenerateProgressBar();
          spc.getselectedObject();
          
          PageReference pageRef = new PageReference(enq);
		  Test.setCurrentPage(pageRef); */
          
          
          
       //   Schema.DescribeSObjectResult ob = new Schema.getGlobalDescribe().get(selectedObject).getdescribe();
        
          
              
      
          
      }
      

}